# Generated by Django 5.0.1 on 2024-02-26 11:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_providers', '0002_serviceproviderproduct_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceProviderService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Required', max_length=255, verbose_name='Product Name')),
                ('price', models.DecimalField(decimal_places=2, help_text='Not Required', max_digits=10, verbose_name='Product Price')),
                ('description', models.TextField(blank=True, help_text='Not Required', verbose_name='Product Description')),
                ('icon', models.ImageField(blank=True, help_text='Upload an icon for the service provider service.', null=True, upload_to='service_provider_icons/', verbose_name='Icon')),
                ('service_provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='service_providers.serviceprovider')),
            ],
        ),
        migrations.DeleteModel(
            name='ServiceProviderProduct',
        ),
    ]
