# Generated by Django 5.0.1 on 2024-02-26 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_providers', '0003_serviceproviderservice_delete_serviceproviderproduct'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceproviderservice',
            name='description',
            field=models.TextField(blank=True, help_text='Not Required', verbose_name='Service Description'),
        ),
        migrations.AlterField(
            model_name='serviceproviderservice',
            name='name',
            field=models.CharField(help_text='Required', max_length=255, verbose_name='Service Name'),
        ),
        migrations.AlterField(
            model_name='serviceproviderservice',
            name='price',
            field=models.DecimalField(decimal_places=2, help_text='Not Required', max_digits=10, verbose_name='Service Price'),
        ),
    ]
