# Generated by Django 5.0.1 on 2024-02-26 17:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_providers', '0005_alter_serviceproviderservice_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sociallink',
            name='service_provider',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='social_links', to='service_providers.serviceprovider'),
        ),
    ]
